# Generated by Django 4.2.4 on 2023-08-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('N', 'Natural'), ('J', 'Jurídico')], max_length=1)),
                ('numero_identificacion', models.CharField(max_length=20, unique=True)),
                ('tipo_identificacion', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('NIT', 'Número de identificación tributaria'), ('TI', 'Tarjeta de Identidad')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_direccion', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('U', 'Urbano'), ('R', 'Rural')], max_length=1)),
                ('numero_catastral', models.CharField(max_length=30, unique=True)),
                ('numero_matricula_inmobiliaria', models.CharField(max_length=30, unique=True)),
                ('propietarios', models.ManyToManyField(related_name='predios', to='predios.propietario')),
            ],
        ),
    ]
