# Generated by Django 4.2.4 on 2023-08-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='tipo',
            field=models.CharField(choices=[('N', 'Natural'), ('J', 'Juridica')], max_length=10),
        ),
    ]
