# Generated by Django 4.2.4 on 2023-08-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predios', '0002_alter_propietario_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predio',
            old_name='tipo',
            new_name='tipo_predio',
        ),
        migrations.AlterField(
            model_name='propietario',
            name='tipo',
            field=models.CharField(choices=[('N', 'Natural'), ('J', 'Juridica')], max_length=1),
        ),
    ]
