# Generated by Django 4.2.4 on 2023-08-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predios', '0003_rename_tipo_predio_tipo_predio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predio',
            name='tipo_predio',
            field=models.CharField(choices=[('Urbano', 'Urbano'), ('Rural', 'Rural')], max_length=10),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='tipo',
            field=models.CharField(choices=[('Natural', 'Natural'), ('Juridica', 'Juridica')], max_length=10),
        ),
    ]
